#!/bin/bash
#SBATCH --export=ALL # export all environment variables to the batch job.
#SBATCH -p mrcq # submit to the serial queue
#SBATCH -A Research_Project-MRC190311 # research project to submit under.
#SBATCH --mail-type=END # send email at job completion
#SBATCH --output=JobReports/07LSDCgenecorr-%j.out
#SBATCH --error=JobReports/07LSDCgenecorr-%j.err
#SBATCH --job-name=07LSDCgenecorr
#SBATCH --nodes=1
#SBATCH --mem=10G
#SBATCH --ntasks=16
#SBATCH --time=0-10:00:00

#####################################################################################################################

#####################################################################################################################

timetemp=$(date -u +%Y-%m-%d_%H-%M)
exec &> >(tee ${LDSCresPath}/logs/logs07LDSCres_log${timetemp}_${phenotype}.log)

module purge
source "/gpfs/ts0/shared/software/Miniconda3/23.5.2-0/etc/profile.d/conda.sh"
conda activate ldsc
LDSC="/lustre/home/sww208/Software/ldsc"

source $1

cd ${LDSCresPath} || exit 1

# LD Score Regression
# check if every phenotyps comes with the .sumstats.gz file

# By using the sumstats generated manully
# for phenotype in DNAmAgeSD DNAmAgessSD PhenoAgeSD PhenoAgessSD DunedinPACESD DunedinPACEssSD
# do
#     if [ -f ${LDSCresPath}/LDSC_${phenotype}/${phenotype}_manually.sumstats.gz ]; then
#         echo "LDSC sumstats file for ${phenotype} generated by MSS exists."
#     else
#         echo "LDSC sumstats file for ${phenotype} does not exist. Please check the 06-LDSCheritability.sh."
#         exit 1
#     fi
# done

# echo "Running LDSC gene correlation among epigenetic phenotypes..."
# mkdir -p LDSC_GeneCorr
# phenos=("DNAmAgeSD" "DNAmAgessSD" "PhenoAgeSD" "PhenoAgessSD" "DunedinPACESD" "DunedinPACEssSD")
# for ((i=0; i<${#phenos[@]}-1; i++)); do
#       for ((j=i+1; j<${#phenos[@]}; j++)); do
#           echo " Estimating the genetic correlation between ${phenos[i]} and ${phenos[j]}"
          
#           epiAgeOne="./LDSC_${phenos[i]}/${phenos[i]}_manually.sumstats.gz"
#           epiAgeTwo="./LDSC_${phenos[j]}/${phenos[j]}_manually.sumstats.gz"
#           outFile="./LDSC_GeneCorr/${phenos[i]}_vs_${phenos[j]}_byhand"
          
#           ${LDSC}/ldsc.py \
#             --rg ${epiAgeOne},${epiAgeTwo} \
#             --ref-ld-chr ${HomePath}/Resources/baselineLD_v2.2/baselineLD. \
#             --w-ld-chr ${HomePath}/Resources/1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. \
#             --out ${outFile}
#       done
# done




# By using the sumstats generated by the MSS package
for phenotype in DNAmAgeSD DNAmAgessSD PhenoAgeSD PhenoAgessSD DunedinPACESD DunedinPACEssSD
do
    if [ -f ${LDSCresPath}/LDSC_${phenotype}/${phenotype}_byR.sumstats.gz ]; then
        echo "LDSC sumstats file for ${phenotype} generated by MSS exists."
    else
        echo "LDSC sumstats file for ${phenotype} does not exist. Please check the 06-LDSCheritability.sh."
        exit 1
    fi
done

echo "Running LDSC gene correlation among epigenetic phenotypes..."
mkdir -p LDSC_GeneCorr
phenos=("DNAmAgeSD" "DNAmAgessSD" "PhenoAgeSD" "PhenoAgessSD" "DunedinPACESD" "DunedinPACEssSD")
for ((i=0; i<${#phenos[@]}-1; i++)); do
      for ((j=i+1; j<${#phenos[@]}; j++)); do
          echo " Estimating the genetic correlation between ${phenos[i]} and ${phenos[j]}"
          
          epiAgeOne="./LDSC_${phenos[i]}/${phenos[i]}_byR.sumstats.gz"
          epiAgeTwo="./LDSC_${phenos[j]}/${phenos[j]}_byR.sumstats.gz"
          outFile="./LDSC_GeneCorr/${phenos[i]}_vs_${phenos[j]}_byR"
          
          ${LDSC}/ldsc.py \
            --rg ${epiAgeOne},${epiAgeTwo} \
            --ref-ld-chr ${HomePath}/Resources/baselineLD_v2.2/baselineLD. \
            --w-ld-chr ${HomePath}/Resources/1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. \
            --out ${outFile}
      done
done




# information
echo " "
# echo "=========The Estimated Genetic Correlation across all the phenotypes======="
# echo "Session one made by hand========================================================"
# for ((i=0; i<${#phenos[@]}-1; i++)); do
#       for ((j=i+1; j<${#phenos[@]}; j++)); do
#           echo "${phenos[i]} and ${phenos[j]}------------------------------------"
#           outFile="./LDSC_GeneCorr/${phenos[i]}_vs_${phenos[j]}_byhand"
#           grep "Genetic Correlation:" ${outFile}.log
#           grep "Z-score:" ${outFile}.log
#           grep "P:" ${outFile}.log
#           echo ""
#       done
# done
echo "Session two made by MSS========================================================"
for ((i=0; i<${#phenos[@]}-1; i++)); do
      for ((j=i+1; j<${#phenos[@]}; j++)); do
          echo "${phenos[i]} and ${phenos[j]}------------------------------------"

          outFile="./LDSC_GeneCorr/${phenos[i]}_vs_${phenos[j]}_byR"
          
          grep "Genetic Correlation:" ${outFile}.log
          grep "Z-score:" ${outFile}.log
          grep "P:" ${outFile}.log
          echo ""
      done
done
echo "============================================================================"

echo "Successfully completed the Genetic Correlation Analysis among all the epi age acc."